source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'LifecycleHooks_Example' do

  pod 'LifecycleHooks', :path => '../'
  
  target 'LifecycleHooks_Tests' do
     
     inherit! :search_paths

  end

end
