source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LifecycleHooks_Example', :exclusive => true do
  pod 'LifecycleHooks', :path => '../'
end

target 'LifecycleHooks_Tests', :exclusive => true do
  pod 'LifecycleHooks', :path => '../'

  
end
